name 'coxmediagroup-puppetboard'
version '1.1.0cox1'
source 'git://github.com/jantman/puppet-module-puppetboard.git'
author 'Spencer Krum'
description 'Install and configure PuppetBoard - coxmediagroup internal fork'
summary 'Install and configure PuppetBoard - coxmediagroup internal fork'
license 'ASL 2.0'
project_page 'https://github.com/jantman/puppet-module-puppetboard'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/vcsrepo', '>= 0.1.2'
dependency 'puppetlabs/apache', '>=0.9.0'
